AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: (AppsyncS3DeleteObjectFn) Appsync S3 func to delete objects

Parameters:
  Environment:
    Type: String
  ArtifactBucketName:
    Type: String
    Default: ''
  ArtifactBucketPath:
    Type: String
    Default: ''

Globals:
  Function:
    Timeout: 60
    Tracing: Active
    Tags:
      Category: Appsync

Resources:
  LogSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Ref LogGroup
      FilterPattern: '-"START RequestId:" -"END RequestId:" -"REPORT RequestId"'
      DestinationArn:
        Fn::ImportValue: !Sub ${Environment}:LogsDestinationArn

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AppsyncS3DeleteObjectFn}
      RetentionInDays: 365

  AppsyncS3DeleteObjectFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-AppsyncS3DeleteObjectFn
      Description: !Sub '(${Environment}) Appsync S3 func to delete objects'
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AWSXrayWriteOnlyAccess
      Runtime: go1.x
      CodeUri: ./main.zip
      Handler: main
      MemorySize: 128
      Environment:
        Variables:
          ENVIRONMENT: !Sub ${Environment}
          LOG_LEVEL: info
          XRAY_LOG_LEVEL: trace
          FILES_BUCKET: !Sub ${Environment}-ee-ad-files
